### ISSUE TITLE
I keep getting an execution error: System Events got an error: osascript is not allowed to send keystrokes. (1002)

### ISSUE THREAD

**Issue by tixastronauta** [johan456789/tdm-via-ssh#1]
I've been trying to remote execute the osascript but most of the times it just doesnt work.. This is the error I get:

```
execution error: System Events got an error: osascript is not allowed to send keystrokes. (1002)
```

Any idea?

**Comment by johan456789** [comment]
Did you try [this](https://github.com/jozanza/p8/issues/2#issuecomment-613852701)? Give Terminal permission.
